import type { InvestorProfile, StartupProfile } from "@/lib/types";

const t0 = "2026-01-01T00:00:00.000Z";

export const sampleInvestors: InvestorProfile[] = [
  {
    id: "inv_atlas",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Maya",
    lastName: "Shah",
    investorType: "VC",
    role: "Partner",
    firmName: "Atlas Ventures",
    website: "https://example.com/atlas",
    contactEmail: "partners@atlas.example",
    sectorFocus: ["B2B SaaS", "Enterprise solutions", "AI/ML"],
    stageFocus: ["Pre-seed", "Seed", "Series A"],
    regions: ["North America", "Europe"],
    checkSizeUsdMin: 250_000,
    checkSizeUsdMax: 3_000_000,
    thesisSummary: "Early technical teams building durable B2B workflows.",
    valueAddSummary: "Go-to-market, hiring, and enterprise design partners."
  },
  {
    id: "inv_aurora",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Rohan",
    lastName: "Gupta",
    investorType: "VC",
    role: "Principal",
    firmName: "Aurora Capital",
    website: "https://example.com/aurora",
    contactEmail: "team@aurora.example",
    sectorFocus: ["Climatetech", "Fintech", "Consumer Internet"],
    stageFocus: ["Seed", "Series A", "Series B"],
    regions: ["North America", "LATAM"],
    checkSizeUsdMin: 1_000_000,
    checkSizeUsdMax: 8_000_000,
    thesisSummary: "Category-defining companies with clear unit economics.",
    valueAddSummary: "Growth playbooks, pricing, and capital strategy."
  },
  {
    id: "inv_northstar",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Ananya",
    lastName: "Iyer",
    investorType: "VC",
    role: "Partner",
    firmName: "Northstar Partners",
    website: "https://example.com/northstar",
    contactEmail: "intro@northstar.example",
    sectorFocus: ["Healthtech", "AI/ML"],
    stageFocus: ["Seed", "Series A"],
    regions: ["Europe", "MENA"],
    checkSizeUsdMin: 500_000,
    checkSizeUsdMax: 5_000_000,
    thesisSummary: "Healthcare delivery and infrastructure with measurable outcomes.",
    valueAddSummary: "Regulatory guidance and provider partnerships."
  },
  {
    id: "inv_summit",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Kabir",
    lastName: "Jain",
    investorType: "MicroVC",
    role: "Associate",
    firmName: "Summit Seed",
    website: "https://example.com/summit",
    contactEmail: "hello@summit.example",
    sectorFocus: ["Consumer Products", "Consumer Internet", "Others"],
    stageFocus: ["Pre-seed", "Seed"],
    regions: ["APAC", "Remote/Global"],
    checkSizeUsdMin: 100_000,
    checkSizeUsdMax: 1_250_000,
    thesisSummary: "Consumer experiences with strong engagement loops.",
    valueAddSummary: "Community growth and creator-led distribution."
  },
  {
    id: "inv_keystone",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Neha",
    lastName: "Kapoor",
    investorType: "VC",
    role: "MD",
    firmName: "Keystone Growth",
    website: "https://example.com/keystone",
    contactEmail: "ops@keystone.example",
    sectorFocus: ["B2B SaaS", "Fintech"],
    stageFocus: ["Series B", "Growth", "Any"],
    regions: ["North America"],
    checkSizeUsdMin: 10_000_000,
    checkSizeUsdMax: 50_000_000,
    thesisSummary: "Scaling proven revenue engines with efficient growth.",
    valueAddSummary: "Metrics operating system and CFO network."
  },
  {
    id: "inv_blueharbor",
    createdAt: t0,
    updatedAt: t0,
    firstName: "Vihaan",
    lastName: "Rao",
    investorType: "Family Office",
    role: "GP",
    firmName: "Blue Harbor Ventures",
    website: "https://example.com/blueharbor",
    contactEmail: "partners@blueharbor.example",
    sectorFocus: ["Climatetech", "Others", "AI/ML"],
    stageFocus: ["Pre-seed", "Seed", "Series A"],
    regions: ["Europe", "Africa", "Remote/Global"],
    checkSizeUsdMin: 300_000,
    checkSizeUsdMax: 2_500_000,
    thesisSummary: "Climate adaptation, automation, and infrastructure resilience.",
    valueAddSummary: "Pilot programs and technical diligence."
  }
];

export const sampleStartups: StartupProfile[] = [
  {
    id: "stp_cascade",
    createdAt: t0,
    updatedAt: t0,
    companyName: "CascadeHQ",
    website: "https://example.com/cascade",
    contactEmail: "founders@cascade.example",
    sector: "B2B SaaS",
    stage: "Seed",
    regions: ["North America"],
    fundingAskUsdMin: 1_500_000,
    fundingAskUsdMax: 2_500_000,
    tractionSummary: "50+ design partners, $18k MRR, 8% MoM growth.",
    productSummary: "Workflow automation for finance ops teams."
  },
  {
    id: "stp_helios",
    createdAt: t0,
    updatedAt: t0,
    companyName: "HeliosGrid",
    website: "https://example.com/helios",
    contactEmail: "team@helios.example",
    sector: "Climate",
    stage: "Series A",
    regions: ["Europe"],
    fundingAskUsdMin: 6_000_000,
    fundingAskUsdMax: 9_000_000,
    tractionSummary: "Deployed in 3 cities, 12-month pipeline with utilities.",
    productSummary: "Grid analytics to reduce downtime and enable renewables."
  },
  {
    id: "stp_mintleaf",
    createdAt: t0,
    updatedAt: t0,
    companyName: "MintLeaf",
    website: "https://example.com/mintleaf",
    contactEmail: "hello@mintleaf.example",
    sector: "HealthTech",
    stage: "Seed",
    regions: ["MENA", "Europe"],
    fundingAskUsdMin: 2_000_000,
    fundingAskUsdMax: 3_500_000,
    tractionSummary: "Clinics onboarded across 2 countries; NPS 58.",
    productSummary: "Patient engagement and scheduling with AI triage."
  },
  {
    id: "stp_siliconforge",
    createdAt: t0,
    updatedAt: t0,
    companyName: "SiliconForge",
    website: "https://example.com/siliconforge",
    contactEmail: "contact@siliconforge.example",
    sector: "DevTools",
    stage: "Pre-seed",
    regions: ["Remote/Global"],
    fundingAskUsdMin: 500_000,
    fundingAskUsdMax: 1_200_000,
    tractionSummary: "4k weekly active developers; open-source adoption.",
    productSummary: "CI debugging and performance regression detection."
  },
  {
    id: "stp_riverpay",
    createdAt: t0,
    updatedAt: t0,
    companyName: "RiverPay",
    website: "https://example.com/riverpay",
    contactEmail: "founders@riverpay.example",
    sector: "FinTech",
    stage: "Series B",
    regions: ["North America"],
    fundingAskUsdMin: 15_000_000,
    fundingAskUsdMax: 25_000_000,
    tractionSummary: "$18M ARR, 120% net revenue retention.",
    productSummary: "Payments and treasury stack for vertical SaaS."
  }
];

